version: 2
jobs:
  setup_repo_tags:
    docker:
    - image: alpine:latest
    steps:
    - run:
        name: Install dependencies
        command: apk add --no-cache git openssh-client
    - checkout
    - run:
        name: Add Postfix remote
        command: git remote add postfix https://github.com/vdukhovni/postfix.git
    - run:
        name: Push latest three tags
        command: |
          set -euo pipefail

          ALL_TAGS=$(git ls-remote -q --tags --refs postfix | sed -nE 's#^[0-9a-f]{40}\trefs/tags/v([0-9]+\.[0-9]+\.[0-9]+)$#\1#p')
          LATEST_MINOR_VERSIONS=$(echo "${ALL_TAGS}" | sed -E 's#^([0-9]+\.[0-9]+)\.[0-9]+$#\1#' | sort -V -u | tail -n 3)

          for MINOR_VERSION in ${LATEST_MINOR_VERSIONS}; do
            LATEST_TAG_FOR_MINOR_VERSION=$(echo "${ALL_TAGS}" | grep '^'"${MINOR_VERSION}"'\.' | sort -V | tail -n 1)
            git tag --force "${LATEST_TAG_FOR_MINOR_VERSION}" HEAD
            git push --force origin "${LATEST_TAG_FOR_MINOR_VERSION}"
          done
workflows:
  version: 2
  setup_repo_tags:
    jobs:
    - setup_repo_tags:
        filters:
          branches:
            only:
            - master
  nightly:
    jobs:
    - setup_repo_tags
    triggers:
    - schedule:
        cron: "0 2 * * *"
        filters:
          branches:
            only:
              master
